### ISSUE TITLE
1.3 Browse menu list options component

### ISSUE THREAD

**Issue by nbarton76** [KC-LCW-Jan-23-Classroom/liftoff-angular-in-the-outfield#26]

**Comment by nbarton76** [comment]
Probably doesn’t need to actually filter movies yet, just build how it looks
Drop-down menus? Buttons?
Check API free tier to see what we’ll be able to filter by
Genre
Streaming service
Decade
Runtime
Rating
Filter out already-watched movies
Decide on how many options are in each drop-down (like which genres to list, etc.)

**Comment by e-karr** [comment]
> Probably doesn’t need to actually filter movies yet, just build how it looks Drop-down menus? Buttons? Check API free tier to see what we’ll be able to filter by Genre Streaming service Decade Runtime Rating Filter out already-watched movies Decide on how many options are in each drop-down (like which genres to list, etc.)

Definitely doesn't need functionality by Wednesday! I would just use placeholder categories for now and we can always edit the categories later based on what the API gives us.

**Comment by nbarton76** [comment]
> Definitely doesn't need functionality by Wednesday! I would just use placeholder categories for now and we can always edit the categories later based on what the API gives us.

I'm glad you said that. Some of the titles can definitely be tweaked and easily changed.
